### ISSUE TITLE
another step: add **test users** in OAuth consent screen

### ISSUE THREAD

**Issue by WinterSong** [JulienMasson/org-gtasks#11]
in [Obtaining Google credentials](https://github.com/JulienMasson/org-gtasks#obtaining-google-credentials), another step is required: add your own as **test users** in OAuth consent screen. BTW thanks for such a great tool.

**Comment by JulienMasson** [comment]
Hi @WinterSong,

Thanks for your feedback, very sorry to answer you late, I've been very busy and I forgot to answer you ...

Can you please send me PR with the new step in README.org ?

Have a nice day

**Comment by JulienMasson** [comment]
Changes merged here: https://github.com/JulienMasson/org-gtasks/pull/12
