### ISSUE TITLE
Add the deadline timestamp using the "due" field in the API 

### ISSUE THREAD

**Issue by maikol-solis** [JulienMasson/org-gtasks#13]
Hi! 

First, this package is incredibly useful. I discovered today, and I am trying to make it a part of my workflow.  

Second, I noticed that all the task retrieved in the org files have this format. 

```
* TODO My task
  :PROPERTIES:
  :ID: abcdefg
  :END:
```

It would awesome if the package could add the deadline date 

```
* TODO My task
  DEADLINE: <2021-09-30 08:00>
  :PROPERTIES:
  :ID: abcdefg
  :END:
```

In the API documentation (https://developers.google.com/tasks/reference/rest/v1/tasks/list) there is a field called "due" with the timestamp of the task deadline. Maybe it could be parsed to org mode in the same way as the completed timestamp. 

Thanks.

**Comment by reedspool** [comment]
+1 though in my workflow, I'm more concerned with the opposite direction, posting tasks to gtasks with date+time info from org. I might take a swing at this if the maintainer doesn't respond soon.

**Comment by JulienMasson** [comment]
Hi @maikol-solis sorry for the late reply, I just come back from vacations.

Yes I think it should not be difficult to implement.

I'm a little bit busy but I will try to do that asap.

Or if you already have something please send me a Pull-Request :)
