### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by tazjin** [JulienMasson/org-gtasks#3]
Hey, thanks for making this!

Quick question: Is this project GPL-licensed? The comment in the main elisp file talks mostly about the license of Emacs itself, but I guess that's the implication?

It would be great if you could add a LICENSE file! Thanks :)

**Comment by boynux** [comment]
I second that question, would you please provide a license so I know how can I use/adapt your great work for my personal use?

Thank you!

**Comment by JulienMasson** [comment]
Hi guys,

Sorry for the late reply.
Yes sure, I will add the GPL license on this project.

Feel free to use/fork/hack it :)
I am not active on this project now but you can still send me pull-request.
I'll be happy to review/merge them.

Thanks
